version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: uni_schedule_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: schedule_db
      POSTGRES_USER: schedule_user
      POSTGRES_PASSWORD: schedule_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
