spring.application.name=Schedule
server.port=8090

spring.datasource.url = jdbc:postgresql://localhost:5432/schedule_db
spring.datasource.username = schedule_user
spring.datasource.password = schedule_pass

spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.show-sql = true

logging.level.root = INFO
#spring.sql.init.mode=always
#http://localhost:8090/swagger-ui.html