spring.application.name=Schedule
server.port=8090

spring.datasource.url = jdbc:postgresql://localhost:5432/schedule_db
spring.datasource.username = schedule_user
spring.datasource.password = schedule_pass

spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.show-sql = true

jwt.secret=zR4Wv79PzK9vQYyYyL8M2N5B3V1C9X0Z8A7S6D5F4G3H2J1K0L9M8N7B6V5C4X3Z2A1S2D3F4G5H6J7K8L9
jwt.expiration-ms=3600000


logging.level.root = INFO
#spring.sql.init.mode=always
#http://localhost:8090/swagger-ui.html

#                        admin
#                        admin123